version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/guides:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Port for Docusaurus
    ports:
      - "3000:3000"

    # Set up the network
    network_mode: bridge
